name: Check format

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
      with:
         submodules: true
    - name: Check Cargo availability
      run: cargo --version
    - name: Check Formatting
      run: cargo fmt -- --check
